#!/usr/bin/env python3
"""
export_artifacts.py
-------------------
Export all project artifacts to machine-readable formats (PDF, MD, JSON).
Useful for: Obsidian second brain, NotebookLM, AI tool ingestion.

Usage:
    uv run python scripts/export_artifacts.py

Output:
    docs/exports/
      notebooks/           ← all 12 notebooks as PDF
      reports/             ← index/report/presentation as PDF
      zh-tram-flow.md      ← Obsidian import with YAML frontmatter
      project_summary.json ← machine-readable metadata
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

# ─── Paths ───────────────────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent.parent
NOTEBOOKS_DIR = ROOT / "notebooks"
PUBLIC_DIR = ROOT / "public"
EXPORTS_DIR = ROOT / "docs" / "exports"
PORTFOLIO_MD = PUBLIC_DIR / "md" / "portfolio.md"

EXPORTS_DIR.mkdir(parents=True, exist_ok=True)
(EXPORTS_DIR / "notebooks").mkdir(exist_ok=True)
(EXPORTS_DIR / "reports").mkdir(exist_ok=True)

# ─── Export Notebooks to PDF ────────────────────────────────────────────────

print("📓 Exporting notebooks to PDF...")

notebooks = sorted(NOTEBOOKS_DIR.glob("*.ipynb"))
for nb in notebooks:
    out = EXPORTS_DIR / "notebooks" / f"{nb.stem}.pdf"
    cmd = [
        "jupyter", "nbconvert",
        "--to", "pdf",
        "--no-input",
        "--output-dir", str(EXPORTS_DIR / "notebooks"),
        "--output", nb.stem,
        str(nb),
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
        print(f"  ✓ {nb.name} → {out.name}")
    except subprocess.CalledProcessError as e:
        print(f"  ✗ {nb.name}: {e.stderr.decode()[:100]}")
    except FileNotFoundError:
        print(f"  ⚠ jupyter nbconvert not found. Install: pip install nbconvert")
        break

# ─── Export Reports to PDF ──────────────────────────────────────────────────

print("\n📊 Exporting reports to PDF...")

reports = [
    (PUBLIC_DIR / "report.html", "report"),
    (PUBLIC_DIR / "presentation.html", "presentation"),
]

for html_file, output_name in reports:
    if not html_file.exists():
        print(f"  ⚠ {html_file.name} not found, skipping")
        continue

    out = EXPORTS_DIR / "reports" / f"{output_name}.pdf"
    # Using weasyprint if available, otherwise note that it's optional
    cmd = ["weasyprint", str(html_file), str(out)]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
        print(f"  ✓ {html_file.name} → {out.name}")
    except FileNotFoundError:
        print(f"  ⚠ weasyprint not found (optional). Install: pip install weasyprint")
        # Copy HTML as fallback
        import shutil
        shutil.copy(html_file, EXPORTS_DIR / "reports" / f"{output_name}.html")
        print(f"     → Copied HTML instead: {output_name}.html")
    except subprocess.CalledProcessError as e:
        print(f"  ✗ {html_file.name}: conversion failed")

# ─── Create Obsidian Frontmatter MD ─────────────────────────────────────────

print("\n🧠 Creating Obsidian import file...")

obsidian_md = EXPORTS_DIR / "zh-tram-flow.md"

# Read portfolio.md for content
portfolio_content = ""
if PORTFOLIO_MD.exists():
    portfolio_content = PORTFOLIO_MD.read_text(encoding="utf-8")

obsidian_content = f"""---
project: Zurich Tram Flow
slug: zh-tram-flow
type: DANSC
status: phase-4-complete
phase: Prediction & Deployment
stack: [Python, Polars, Pandas, LightGBM, Plotly, Streamlit, Jupyter, uv, Git]
period: 2023-2025
rows: 94400000
findings: 63
model_mae: 18.56
created: 2026-05-11
updated: {datetime.now().isoformat()}
tags: [portfolio, data-science, transit, zürich, lightgbm, streamlit, ml]
artifacts:
  landing: https://kaywiegand.github.io/zh-tram-flow/landingpage.html
  dashboard: https://zh-tram-flow.streamlit.app
  report: https://kaywiegand.github.io/zh-tram-flow/report.html
  presentation: https://kaywiegand.github.io/zh-tram-flow/presentation.html
  github: https://github.com/kaywiegand/zh-tram-flow
  data-engineering: https://github.com/kaywiegand/zh-tram-data
notebooks: 12
notebooks-pdf: docs/exports/notebooks/
reports-pdf: docs/exports/reports/
---

# Zurich Tram Flow

{portfolio_content}

---

## Machine Exports

This file was generated by `scripts/export_artifacts.py` for use in:
- **Obsidian**: Paste this content into an `.md` file in your vault
- **AI Tools**: Use PDF exports in NotebookLM, Claude, or GPT for analysis
- **Archive**: All artifacts in machine-readable format

### Files Generated

- `docs/exports/notebooks/` — All 12 Jupyter notebooks as PDF
- `docs/exports/reports/` — Full report, presentation, landing page as PDF
- `docs/exports/zh-tram-flow.md` — This file (Obsidian import)
- `docs/exports/project_summary.json` — Structured metadata

### Using in Obsidian

1. Copy content of `zh-tram-flow.md` into your vault
2. YAML frontmatter will be parsed automatically
3. Links point to live artifacts on GitHub Pages + Streamlit Cloud
4. PDFs can be linked locally if imported into vault

---

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} UTC
"""

obsidian_md.write_text(obsidian_content, encoding="utf-8")
print(f"  ✓ {obsidian_md.name} created")

# ─── Create project_summary.json ────────────────────────────────────────────

print("\n📋 Creating project metadata JSON...")

project_meta = {
    "project": "Zurich Tram Flow",
    "slug": "zh-tram-flow",
    "type": "DANSC",
    "status": "phase-4-complete",
    "description": "Analysis and prediction of delays in Zürich's tram network",
    "period": "2023-2025",
    "data": {
        "rows_total": 94400000,
        "rows_clean": 85000000,
        "train_rows": 41200000,
        "val_rows": 14300000,
        "test_rows": 29000000,
        "period_start": "2023-01-01",
        "period_end": "2025-12-31",
    },
    "analysis": {
        "findings": 63,
        "notebooks": 12,
        "key_finding": "Delays are predictable (not random) and concentrated at periphery. Cascade effect (r≥0.85) confirms systemic pattern.",
    },
    "model": {
        "name": "LightGBM v2",
        "features": 34,
        "test_mae": 18.56,
        "test_rmse": 32.4,
        "test_mbe": -0.69,
        "baseline_mae": 50.0,
        "improvement_pct": 62.88,
    },
    "stack": [
        "Python 3.10+",
        "Polars (data processing)",
        "Pandas (compatibility)",
        "LightGBM (modeling)",
        "Plotly (visualization)",
        "Streamlit (dashboard)",
        "Jupyter (analysis)",
        "uv (dependency management)",
        "Git (version control)",
    ],
    "artifacts": {
        "landing_page": "https://kaywiegand.github.io/zh-tram-flow/landingpage.html",
        "dashboard": "https://zh-tram-flow.streamlit.app",
        "full_report": "https://kaywiegand.github.io/zh-tram-flow/report.html",
        "presentation": "https://kaywiegand.github.io/zh-tram-flow/presentation.html",
        "github": "https://github.com/kaywiegand/zh-tram-flow",
        "data_engineering": "https://github.com/kaywiegand/zh-tram-data",
    },
    "exports": {
        "notebooks_pdf": "docs/exports/notebooks/",
        "reports_pdf": "docs/exports/reports/",
        "obsidian_md": "docs/exports/zh-tram-flow.md",
        "metadata_json": "docs/exports/project_summary.json",
    },
    "generated": datetime.now().isoformat(),
}

summary_json = EXPORTS_DIR / "project_summary.json"
summary_json.write_text(json.dumps(project_meta, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"  ✓ {summary_json.name} created")

# ─── Summary ───────────────────────────────────────────────────────────────

print(f"\n✅ Export complete!")
print(f"\nOutput directory: {EXPORTS_DIR}")
print(f"  📁 notebooks/     — {len(list((EXPORTS_DIR/'notebooks').glob('*.pdf')))} PDFs")
print(f"  📁 reports/       — {len(list((EXPORTS_DIR/'reports').glob('*')))} files")
print(f"  📄 zh-tram-flow.md    — Obsidian import (YAML + content)")
print(f"  📋 project_summary.json — Metadata for AI tools")
